### PR TITLE
fix: 修复录屏计时图标偏移

### PR DESCRIPTION
**Pull request by hundundadi**
Description: 修复录屏计时图标偏移

Log: 修复录屏计时图标偏移

### CODE REVIEW

**Comment by hundundadi** [comment]
check apicheck

**Comment by hundundadi** [comment]
check /apicheck

**Comment by pengfeixx** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by HeeMingYang — APPROVED** [review]
/+1

**Pull request merged**
