### PR TITLE
fix: 修复截长图，双击区域外，未响应保存截图

### PR DESCRIPTION
**Pull request by hundundadi**
Description: 修复截长图，双击区域外，未响应保存截图

Log: 修复截长图，双击区域外，未响应保存截图

### CODE REVIEW

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by HeeMingYang — APPROVED** [review]
/+1

**Pull request merged**
