### PR TITLE
fix: v23插件需要重新安装下翻译

### PR DESCRIPTION
**Pull request by hundundadi**
Description: v23插件需要重新安装下翻译

Log: v23插件需要重新安装下翻译

### CODE REVIEW

**Comment by jeffshuai** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by pengfeixx — APPROVED** [review]
/+1

**Pull request merged**
