### PR TITLE
fix: 修复通知中心中截图录屏提示信息未国际化

### PR DESCRIPTION
**Pull request by hundundadi**
Description: 应用名称没有tr

Log: 修复通知中心中截图录屏提示信息未国际化

Bug: https://pms.uniontech.com/bug-view-200517.html

### CODE REVIEW

**Comment by pengfeixx** [comment]
[Fail原因] N/A
[Review结论] Pass
[是否满足commit提交规范] Y
[是否满足兼容性要求] Y
[是否满足编码规范] Y

**Comment by jeffshuai** [comment]
[Fail原因] N/A
[Review结论] Pass
[是否满足commit提交规范] Y
[是否满足兼容性要求] Y
[是否满足编码规范] Y

**Review by lzwind — APPROVED** [review]
/+1

**Pull request merged**
