### PR TITLE
feat: 录屏保存优化功能实现

### PR DESCRIPTION
**Pull request by hundundadi**
Description: 录屏保存优化功能实现

Log: 录屏保存优化功能实现

Task: https://pms.uniontech.com/task-view-169547.html
      https://pms.uniontech.com/task-view-169549.html

### CODE REVIEW

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by HeeMingYang — APPROVED** [review]
/+1

**Pull request merged**
