### PR TITLE
fix: 修复勾选"显示鼠标点击"，录屏时却未显示

### PR DESCRIPTION
**Pull request by hundundadi**
Description: 没有通过配置文件初始化鼠标点击的选项

Log: 修复勾选"显示鼠标点击"，录屏时却未显示

Bug: https://pms.uniontech.com/bug-view-199657.html

### CODE REVIEW

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by jeffshuai** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by jeffshuai** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by lzwind — APPROVED** [review]
/+1

**Pull request merged**
