### PR TITLE
fix: the recorded gif has a grid block shadow

### PR DESCRIPTION
**Pull request by add-uos**
fix the recorded gif has a grid block shadow.
use the color palette optimization.

Log: fix the recorded gif has a grid block shadow.
Bug: https://pms.uniontech.com/bug-view-262443.html

### CODE REVIEW

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by rb-union — COMMENTED** [review]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by lzwind — APPROVED** [review]

**Pull request merged**
