### PR TITLE
fix: 修复4k双屏1.25倍缩放,截图截到工具栏

### PR DESCRIPTION
**Pull request by hundundadi**
Description:  由于工具栏未及时隐藏，导致截图时截到工具栏，现已经更改截图保存方案

Log:  修复4k双屏1.25倍缩放,截图截到工具栏

Bug: https://pms.uniontech.com/bug-view-151133.html

### CODE REVIEW

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by HeeMingYang — APPROVED** [review]
/+1

**Pull request merged**
