### PR TITLE
chore: 还原代码，去除插件翻译的安装

### PR DESCRIPTION
**Pull request by hundundadi**
Description: 还原代码，去除插件翻译的安装

Log: 还原代码，去除插件翻译的安装

### CODE REVIEW

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by jeffshuai** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by pengfeixx — APPROVED** [review]
/+1

**Pull request merged**
