### PR TITLE
fix: Can not Play Recorded mp4 videos on iPhone

### PR DESCRIPTION
**Pull request by myml**
根据社区论坛的用户反馈,录制的视频无法在苹果手机播放
https://bbs.deepin.org/post/245693

Log: 修复录制的视频无法在苹果手机播放

### CODE REVIEW

**Review by hundundadi — COMMENTED** [review]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by HeeMingYang — APPROVED** [review]
/+1

**Pull request merged**
