### PR TITLE
fix: 修复v23贴图工具栏在高缩放比下，工具栏模糊及选项按钮显示不全

### PR DESCRIPTION
**Pull request by hundundadi**
Description: 修复v23贴图工具栏在高缩放比下，工具栏模糊及选项按钮显示不全

Log: 修复v23贴图工具栏在高缩放比下，工具栏模糊及选项按钮显示不全

Bug: https://pms.uniontech.com/bug-view-219447.html
	https://pms.uniontech.com/bug-view-230457.html

### CODE REVIEW

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by wyu71 — APPROVED** [review]
/+1

**Pull request merged**
