### PR TITLE
fix: 修复arm MP4格式录屏保存不成功

### PR DESCRIPTION
**Pull request by hundundadi**
Description: 修复arm MP4格式录屏保存不成功

Log: 修复arm MP4格式录屏保存不成功

Bug: https://pms.uniontech.com/bug-view-172577.html

### CODE REVIEW

**Review by pengfeixx — COMMENTED** [review]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by HeeMingYang — APPROVED** [review]
/+1

**Pull request merged**
