### PR TITLE
fix: don't hardcode /usr/bin path

### PR DESCRIPTION
**Pull request by wineee**
Log: 避免硬编码查找路径，提高可移植性

### CODE REVIEW

**Comment by wineee** [comment]
cc @lzwind

**Review by hundundadi — COMMENTED** [review]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by lzwind — APPROVED** [review]

**Pull request merged**
