### PR TITLE
fix: 将QTimer超时监听换成线程实现

### PR DESCRIPTION
**Pull request by hundundadi**
Description: 将QTimer超时监听换成线程实现

Log: 将QTimer超时监听换成线程实现

### CODE REVIEW

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by pengfeixx** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by HeeMingYang — APPROVED** [review]
/+1

**Pull request merged**
