### PR TITLE
Update deepin-screen-recorder_el.ts

### PR DESCRIPTION
**Pull request by VasilisKos**
Updated Greek translation

### CODE REVIEW

**Comment by BLumia** [comment]
Hi, sorry we only accept translation updates via [Transifex](https://www.transifex.com/linuxdeepin/public/), please submit your translation there, thanks!

**Comment by VasilisKos** [comment]
Well... You could have told me a year ago...!

**Comment by BLumia** [comment]
Sorry, I'm not a part of the deepin team a year ago :/

**Comment by VasilisKos** [comment]
Looks like there's no Screen Recorder app in Transifex. There's a Screen Capture one. Is it that? Have you changed its name?

**Comment by BLumia** [comment]
> Looks like there's no Screen Recorder app in Transifex. There's a Screen Capture one. Is it that? Have you changed its name?

Yes, the [Deepin Screen Capture](https://www.transifex.com/linuxdeepin/deepin-screen-recorder/) one is the correct one. Not sure why the localization team gives it a different name :p

**Pull request closed without merging**
