### PR TITLE
fix: 修复wayland模式下，无法滚动截图

### PR DESCRIPTION
**Pull request by hundundadi**
Description: 修复wayland模式下，无法滚动截图

Log: 修复wayland模式下，无法滚动截图

Bug: https://pms.uniontech.com/bug-view-178451.html

### CODE REVIEW

**Comment by pengfeixx** [comment]
[Fail原因] N/A
[Review结论] Pass
[是否满足commit提交规范] Y
[是否满足兼容性要求] Y
[是否满足编码规范] Y

**Comment by myk1343** [comment]
[Fail原因] N/A
[Review结论] Pass
[是否满足commit提交规范] Y
[是否满足兼容性要求] Y
[是否满足编码规范] Y

**Comment by feeengli** [comment]
[Fail原因] N/A
[Review结论] Pass
[是否满足commit提交规范] Y
[是否满足兼容性要求] Y
[是否满足编码规范] Y

**Review by HeeMingYang — APPROVED** [review]
/+1

**Pull request merged**
