### PR TITLE
fix: 修复截图录屏贴图保存到剪贴板，提示“保存失败”，及独立贴图日志

### PR DESCRIPTION
**Pull request by hundundadi**
Description: 没有更新配置文件

Log: 修复截图录屏贴图保存到剪贴板，提示“保存失败”

### CODE REVIEW

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by jeffshuai** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by pengfeixx — APPROVED** [review]
/+1

**Pull request merged**
