### PR TITLE
chore: （wayland）gstreamer录屏适配hw机型

### PR DESCRIPTION
**Pull request by hundundadi**
Description: hw主板采集的像素格式不同，需特别处理

Log: （wayland）gstreamer录屏适配hw机型

### CODE REVIEW

**Review by zhangwenchaoworking — COMMENTED** [review]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by feeengli — COMMENTED** [review]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by HeeMingYang — APPROVED** [review]
/+1

**Pull request merged**
