### PR TITLE
fix: 快捷全屏录制时，屏蔽3s倒计时，通知消息，及捕捉区域边框

### PR DESCRIPTION
**Pull request by hundundadi**
Description: 快捷全屏录制时，屏蔽3s倒计时，通知消息，及捕捉区域边框

Log: 快捷全屏录制时，屏蔽3s倒计时，通知消息，及捕捉区域边框

Bug: https://pms.uniontech.com/bug-view-213709.html

### CODE REVIEW

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by jeffshuai** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by wyu71 — APPROVED** [review]
/+1

**Pull request merged**
