### PR TITLE
fix: 修复点击滚动截图选项菜单中的选项会触发自动滚动功能

### PR DESCRIPTION
**Pull request by hundundadi**
Description: 修复点击滚动截图选项菜单中的选项会触发自动滚动功能

Log: 修复点击滚动截图选项菜单中的选项会触发自动滚动功能

Bug: https://pms.uniontech.com/bug-view-199335.html

### CODE REVIEW

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by wyu71 — APPROVED** [review]
/+1

**Pull request merged**
