### PR TITLE
refactor: merge code and fix bugs

### PR DESCRIPTION
**Pull request by rb-union**
[refactor: merge code and fix bugs](https://github.com/linuxdeepin/deepin-screen-recorder/commit/872beed1a62a20168ec4e64748d3a6c1c17fe7d5) 

Merge branch master code to develop/snipe,
from https://github.com/linuxdeepin/deepin-screen-recorder/commit/4f965b57b16c4dc60e17943094b8a21a4f6844e8
to https://github.com/linuxdeepin/deepin-screen-recorder/commit/11a359bbdcdbb1730e088ef81b6c128b544af2f3

Merge branch release/eagle code to develop/snipe,
from https://github.com/linuxdeepin/deepin-screen-recorder/commit/732c3c63475563f42eb557db4a6b794972e7bf19
to https://github.com/linuxdeepin/deepin-screen-recorder/commit/78e8a2c9d882741bd9e79d6bae400adee495e054

* Remove deepin-screen-recorder-plugin;
* Update translations;

Log: merge code

### CODE REVIEW

**Comment by pengfeixx** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by starhcq** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Pull request merged**
