### PR TITLE
chore: 调整关键日志位置

### PR DESCRIPTION
**Pull request by hundundadi**
Description: 调整关键日志位置

Log: 调整关键日志位置

### CODE REVIEW

**Comment by pengfeixx** [comment]
[Fail原因] N/A
[Review结论] Pass
[是否满足commit提交规范] Y
[是否满足兼容性要求] Y
[是否满足编码规范] Y

**Comment by feeengli** [comment]
[Fail原因] N/A
[Review结论] Pass
[是否满足commit提交规范] Y
[是否满足兼容性要求] Y
[是否满足编码规范] Y

**Review by HeeMingYang — APPROVED** [review]
/+1

**Pull request merged**
