### PR TITLE
fix: 录屏时不允许改变屏幕分辨率

### PR DESCRIPTION
**Pull request by hundundadi**
Description: 由于开始录屏之前，就会将需要录制的屏幕大小给进去，录制过程中，不允许修改分辨率

Log: 录屏时不允许改变屏幕分辨率

### CODE REVIEW

**Comment by pengfeixx** [comment]
[Fail原因] N/A
[Review结论] Pass
[是否满足commit提交规范] Y
[是否满足兼容性要求] Y
[是否满足编码规范] Y

**Comment by jeffshuai** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by lzwind — APPROVED** [review]
/+1

**Pull request merged**
