### PR TITLE
fix: 修复任务栏设置在侧边，录屏计时图标大小不正确的问题

### PR DESCRIPTION
**Pull request by hundundadi**
Description: 由于录屏计时插件的item widget高度不正确导致

Log: 修复任务栏设置在侧边，录屏计时图标大小不正确的问题

Bug: https://pms.uniontech.com/bug-view-200953.html
     https://pms.uniontech.com/bug-view-200663.html
     https://pms.uniontech.com/bug-view-194037.html

### CODE REVIEW

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by jeffshuai** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by lzwind — APPROVED** [review]
/+1

**Pull request merged**
