### PR TITLE
chore: 105x打开兼容性宏开关

### PR DESCRIPTION
**Pull request by hundundadi**
Description: 由于同窗管有强依赖，需要回落到1054

Log: 105x打开兼容性宏开关

### CODE REVIEW

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by jeffshuai** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by lzwind — APPROVED** [review]
/+1

**Pull request merged**
