### PR TITLE
feat: 兼容性开发

### PR DESCRIPTION
**Pull request by hundundadi**
Description: 1054上remoteaccess协议新增了接口，该接口未同步到低版本，因此做了相关隔离

Log: 兼容性开发

### CODE REVIEW

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by pengfeixx — APPROVED** [review]
/+1

**Pull request merged**
