### PR TITLE
fix: (x11)修复调整捕捉区域后，录制的画面区域不正确

### PR DESCRIPTION
**Pull request by hundundadi**
Description: gstremer中ximagesrc的bug，录制区域的终点有问题

Log: 修复调整捕捉区域后，录制的画面区域不正确

Bug: https://pms.uniontech.com/bug-view-127641.html
        https://pms.uniontech.com/bug-view-127963.html

### CODE REVIEW

**Review by zhangwenchaoworking — COMMENTED** [review]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by zhangwenchaoworking — APPROVED** [review]
/+1

**Review by HeeMingYang — APPROVED** [review]
/+1

**Review by HeeMingYang — APPROVED** [review]
/+1

**Review by HeeMingYang — APPROVED** [review]
/+1

**Review by HeeMingYang — APPROVED** [review]
/+1

**Review by lzwind — APPROVED** [review]
/+1

**Pull request merged**
