### PR TITLE
fix: 更换保存到剪切板的延时方式、添加一些关键日志

### PR DESCRIPTION
**Pull request by hundundadi**
Description: 更换保存到剪切板的延时方式、添加一些关键日志

Log: 更换保存到剪切板的延时方式、添加一些关键日志

Bug: https://pms.uniontech.com/bug-view-170721.html

### CODE REVIEW

**Comment by pengfeixx** [comment]
[Fail原因] N/A
[Review结论] Pass
[是否满足commit提交规范] Y
[是否满足兼容性要求] Y
[是否满足编码规范] Y

**Comment by myk1343** [comment]
[Fail原因] N/A
[Review结论] Pass
[是否满足commit提交规范] Y
[是否满足兼容性要求] Y
[是否满足编码规范] Y

**Review by lzwind — APPROVED** [review]
/+1

**Pull request merged**
