### PR TITLE
chore: 命令行帮助不显示快捷录制全屏

### PR DESCRIPTION
**Pull request by hundundadi**
Description: 命令行帮助不显示快捷录制全屏

Log: 命令行帮助不显示快捷录制全屏

### CODE REVIEW

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by rb-union** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by lzwind — APPROVED** [review]
/+1

**Pull request merged**
