### PR TITLE
fix: (UI) 修复截图&录屏的完成按钮圆角不对

### PR DESCRIPTION
**Pull request by hundundadi**
Description: (UI) 修复截图&录屏的完成按钮圆角不对,去除了两个未使用的依赖

Log: (UI) 修复截图&录屏的完成按钮圆角不对

Bug: https://pms.uniontech.com/bug-view-156653.html

### CODE REVIEW

**Review by pengfeixx — COMMENTED** [review]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by pengfeixx** [comment]
123

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by HeeMingYang — APPROVED** [review]
/+1

**Pull request merged**
