### PR TITLE
chore: update changelog.(5.12.13)

### PR DESCRIPTION
**Pull request by hundundadi**
Description: update changelog.(5.12.13)

Log: update changelog.(5.12.13)

### CODE REVIEW

**Review by wyu71 — APPROVED** [review]
/+1

**Comment by hundundadi** [comment]
merge

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by hundundadi** [comment]
merge

**Pull request merged**
