### PR TITLE
feat: 截图自定义保存路径交互简化功能

### PR DESCRIPTION
**Pull request by hundundadi**
Description: 截图自定义保存路径交互简化功能

Log: 截图自定义保存路径交互简化功能

Task: https://pms.uniontech.com/task-view-241885.html

### CODE REVIEW

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by pengfeixx — APPROVED** [review]
/+1

**Pull request merged**
