### PR TITLE
fix: 优化保存到无权限或已删除的目录的逻辑

### PR DESCRIPTION
**Pull request by hundundadi**
Description: 优化保存到无权限或已删除的目录的逻辑

Log: 优化保存到无权限或已删除的目录的逻辑

### CODE REVIEW

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by pengfeixx — APPROVED** [review]
/+1

**Pull request merged**
