### PR TITLE
fix: 修复托盘区域和个性化-桌面版，插件区域下，截图录屏未进行翻译

### PR DESCRIPTION
**Pull request by hundundadi**
Description: 修复托盘区域和个性化-桌面版，插件区域下，截图录屏未进行翻译

Log: 修复托盘区域和个性化-桌面版，插件区域下，截图录屏未进行翻译

Bug: https://pms.uniontech.com/bug-view-184057.html

### CODE REVIEW

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by pengfeixx — APPROVED** [review]
/+1

**Pull request merged**
