### PR TITLE
fix: 修复录屏时提示段错误，导致无法录屏

### PR DESCRIPTION
**Pull request by hundundadi**
Description: 修复录屏时提示段错误，导致无法录屏

Log: 修复录屏时提示段错误，导致无法录屏

Bug: https://pms.uniontech.com/bug-view-185721.html

### CODE REVIEW

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by jeffshuai** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by pengfeixx — APPROVED** [review]
/+1

**Pull request merged**
