### PR TITLE
feat: v20贴图自定义保存位置优化

### PR DESCRIPTION
**Pull request by hundundadi**
Description: v20贴图自定义保存位置优化；更新了截图配置文件位置

Log: v20贴图自定义保存位置优化

Task: https://pms.uniontech.com/task-view-241885.html

### CODE REVIEW

**Review by pengfeixx — COMMENTED** [review]
[Fail原因] N/A
[Review结论] Pass
[是否满足commit提交规范] Y
[是否满足兼容性要求] Y
[是否满足编码规范] Y

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by lzwind — APPROVED** [review]
/+1

**Pull request merged**
