### PR TITLE
fix: 新增x264编码器是否存在的判断

### PR DESCRIPTION
**Pull request by hundundadi**
Description: 新增x264编码器是否存在的判断

Log: 新增x264编码器是否存在的判断

Bug: https://pms.uniontech.com/bug-view-158335.html

### CODE REVIEW

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by HeeMingYang — APPROVED** [review]
/+1

**Pull request merged**
