### PR TITLE
chore: 增加关键日志

### PR DESCRIPTION
**Pull request by hundundadi**
Description: 增加关键日志

Log: 增加关键日志

### CODE REVIEW

**Comment by pengfeixx** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by HeeMingYang — APPROVED** [review]
/+1

**Pull request merged**
