### PR TITLE
feat: 任务栏插件默认不显示

### PR DESCRIPTION
**Pull request by hundundadi**
Description: 任务栏插件默认不显示

Log: 任务栏插件默认不显示

Task: https://pms.uniontech.com/task-view-223321.html

### CODE REVIEW

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by jeffshuai** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by wyu71 — APPROVED** [review]
/+1

**Pull request merged**
