### PR TITLE
fix: 修复多屏下，工具栏位置不正确

### PR DESCRIPTION
**Pull request by hundundadi**
Description:  未考虑到该场景，场景比较少见

Log:  优化多任务视图界面，选择截图区域卡顿的问题

Bug: https://pms.uniontech.com/bug-view-153867.html

### CODE REVIEW

**Comment by jeffshuai** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by HeeMingYang — APPROVED** [review]
/+1

**Pull request merged**
